#!/usr/bin/env python3
from array import *

ciphertext = "XSIPICTVEQQRGHJUYEXVVISEEFRXRLRPAVEPLPIELLFPGAQZBXEIPXBIVZXQGGBRRXTIYBFPVFCNGHDIOYEBXJSRXUHWPATSZPIDIDZRBRCIOIAMQZRFLFASHIHIEPISEHIBGEYIIWPTPPWQIAFETREXEXEXTDSQNGEWMRQLICZUGRLHPWUKAXHTRMANRXSEFKVOIDYEIELWZPQGBGXCSXSIXVLGOIFLXZXTIVKHLXMEFTVPWGPGEEHIZJBKGPQQRGBWDSYIGBQPWGRNUPPXAVRVSGIDXUXGZRFIAMSQIXIPMVZRUGPHQXYZMPTXTSZWSKSXXTIGXGSRAPBZCAVAZVWICIHIABRCIETBGWPXAEPHYCXAVQXVZVPYYREFXTSEBDPHIEEKEYXUWFNIOFKESXHPVMPWNHRIRSEXBLQBPRFEYCOSZFYYMOEGBSYWEIEOMNIERBPIYGDCCMGPVFEVGGZQYYABGLXUSALFJHQJNNPEAUXUMLPOQCAXGPWEEERXZHQGERTEXTIPHQXYZMPTXTSZWFHPPPKMAMLPLMRQLSQXTIRGHFWQVGAMDEBTYBIDFAXUPLPRFLRWEEEUWVGQZXUSAHZPVQPRVXCSZMPGIEAAVXLSCEFVRLXZRMRREINXDSABGOIHMPXMQXTIPHQXYZMPTXTSZWCKSGMPIEBWDIDZRWATXTEJTVCEZXFXIVMZKGASDIOSZFYYMOEGBSYWFLRIVZZUHRKGLRZSGIVZZUHRMLPHMXNUINEGWRBXSEEHRLMRRQHGAIEIOLAHPZKKWHVLELMXVMGLRZSGUILGOIFLIOFKEARXSMDHCTVECIIQHRZXTEIXEYCEMYOICFGPYXXDEZHGAIOMEGHLWTSZWJBXSMZXUXIIIOYGBZPFDEAVLLVQWGBPWSZKBBRRATMYXXSIDIUTWYSFCRMFPIZEQXGTWUSAPLPXTIEMSDIQOYXKTWXEGBSYAQQHLXHSDOJBXSGARTKIDWURQNWEVKEPTHPQUGFIVTZMGLZVZYBWNGHZXTIELXZGDESMEYEBTEHENLFLNMEOHDIFLIDEXPBYXSIYYYMMAPQGBFTPXURTVSYGQVALXSEFLNOIMIQRGAIQSOYFHJDSYYPAHPFMXRUYEAQGNGEWPMKEXIELMXJXATPXRRXHZRSSVGKSSZIFMEYHURSHVXIPTHUPTGPIOTXPENSHMLZANIFMXZTDSGXGEPUFRKXJEZHFXGFVUXLBRMSFLBNVWEIWNGHZYDXRVLYSXSTR"

m6 = ["", "", "", "", "", ""]
m7 = ["", "", "", "", "", "", ""]
m8 = ["", "", "", "", "", "", "", ""]

for i in range(5):
    m6[i] = ciphertext[i::6]

for i in range(6):
    m7[i] = ciphertext[i::7]

for i in range(7):
    m8[i] = ciphertext[i::8]
